### ISSUE TITLE
Error while connecting to Firefly

### ISSUE THREAD

**Issue by nr458h** [YunoHost-Apps/firefly-iii-di_ynh#5]
Hello,

I'm facing an error while trying to use the Importer with my selfhosted Firefly-instance. I try to connect via the public URL, after that I get the following error:

`Server error: POST https://your.domain.tls/firefly/oauth/token resulted in a 500 Internal Server Error response: <!DOCTYPE html> <html lang="de"> <head> <meta charset="UTF-8"> <meta name="robots" content="noindex, nofollow, n (truncated...)`

I had a look at the official repository, there were also issues with the same error, but they all got fixed some versions ago, so I think it is related to the yunohost app.

If I can provide additional information please feel free :)

Thanks in advance

**Comment by marcoil** [comment]
Hi!
If your Firefly instance is also hosted with Yunohost, can you check that it is enabled for all visitors? If you go to its URL in a browser private session, you should see Firefly's user login page, not Yunohost's page.

Setting Firefly to allow all visitors is necessary for the importer to access it, it's not a security problem because Firefly controls access itself.

**Comment by nr458h** [comment]
The settings via the application menu are:
![image](https://user-images.githubusercontent.com/110965114/236170909-a57b9c35-a160-49b1-bc00-6eea08f8c6eb.png)

also if I connect to my firefly instance via tor there is no redirect to the yunohost sso

**Comment by marcoil** [comment]
That seems correct. Is what you pasted the whole error message? Seeing what was truncated would really help.

**Comment by marcoil** [comment]
> Okay - can you give me some guidance here? On which application the importer or firefly ??

Sorry I wasn't more explicit. In your initial report, there's a server error message, but it ends with `(truncated...)`. Do you see any way of getting the full error message?

Also, if you can go into your importer log directory (it's usually at /var/www/firefly-iii-di/storage/logs), get the log with the error and paste it here or upload it somewhere, it'd be really helpful.

**Comment by hazzamyman** [comment]
I've been having the same issues - same error - word for word. here are my logs:

[2023-05-08 14:11:13] local.ERROR: Client exception when decoding response: Server error: `POST https://firefly.YUNOHOSTDOMAIN/oauth/token` resulted in a `500 Internal Server Error` response:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex, nofollow, n (truncated...)
  
[2023-05-08 14:11:13] local.ERROR: Response from server: "<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex, nofollow, noarchive, noodp, NoImageIndex, noydir">
    <title>Firefly III Exception :(</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <base href="https://firefly.YUNOHOSTDOMAIN/">

    
        <link href="v1/lib/bs/css/bootstrap.min.css?v=" rel="stylesheet" type="text/css" nonce="A1DW819kxJuxc7JiJM7qKQ==">
    <link href="v1/lib/fa/css/font-awesome.min.css?v=" rel="stylesheet" type="text/css" nonce="A1DW819kxJuxc7JiJM7qKQ==">
    <link href="v1/css/daterangepicker.css?v=" rel="stylesheet" type="text/css" nonce="A1DW819kxJuxc7JiJM7qKQ==">

        <link href="v1/lib/adminlte/css/AdminLTE.min.css?v=" rel="stylesheet" type="text/css" nonce="A1DW819kxJuxc7JiJM7qKQ==">
    <link href="v1/lib/adminlte/css/skins/skin-blue-light.min.css?v=" rel="stylesheet" type="text/css" nonce="A1DW819kxJuxc7JiJM7qKQ==">

        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png?v=3e8AboOwbd">
<link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png?v=3e8AboOwbd">
<link rel="manifest" href="manifest.webmanifest?v=3e8AboOwbd">
<link rel="mask-icon" href="safari-pinned-tab.svg" color="#3c8dbc">
<link rel="shortcut icon" href="favicon.ico?v=3e8AboOwbd">
<meta name="apple-mobile-web-app-title" content="Firefly III">
<meta name="application-name" content="Firefly III">
<meta name="msapplication-TileColor" content="#3c8dbc">
<meta name="msapplication-TileImage" content="mstile-144x144.png?v=3e8AboOwbd">
<meta name="theme-color" content="#3c8dbc">

<script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></head>
<body class="container">
<div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">
        <h1><a href="https://firefly.YUNOHOSTDOMAIN"><strong>Firefly</strong>III</a></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">
        <h3 class="text-info">Whoops! An error occurred.</h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">
        <p>
            Unfortunately, this error was not recoverable :(. Firefly III broke. The error is:
        </p>
        <p class="text-danger">
            Expected response code &quot;250/251/252&quot; but got code &quot;553&quot;, with message &quot;553 5.7.1 &lt;email@YUNOHOSTDOMAIN&gt;: Sender address rejected: not logged in&quot;.
        </p>
        <p>
            This error occured in file <span style="font-family: monospace;">/var/www/firefly-iii/app/Jobs/MailError.php</span> on line 103 with code 0.
        </p>
    </div>
</div>

**Comment by marcoil** [comment]
I'm pretty sure that's the same error you get when Firefly is behind Yunohost's user login system, which makes it impossible for the importer to connect to it.

Are both Firefly and the importer in the same machine? Can you make sure that your importer points to Firefly's public URL? If you give it an internal name like localhost or 127.0.0.1 it won't work.

**Comment by OnlyVoidd** [comment]
Hello,

I have about the same error when trying to connect the Data Importer to my Self hosted Yunohost Firefly instance (which is on the same machine).

Here is the message :

### Whoops! 500 :(
Sorry, the Firefly III Data Importer broke down.

### Error message
The "state" returned from your server doesn't match the state that was sent.

### More information
The error occurred in /var/www/firefly-iii-di/app/Http/Controllers/TokenController.php:74.

Here is error in the logs :

`[2023-05-18 18:43:52] local.ERROR: State according to session: ""
[2023-05-18 18:43:52] local.ERROR: State returned in request : "18z3OuVumKg7SjwSkDLbE80alahhob4nAy38bKjf"
[2023-05-18 18:43:52] local.ERROR: The "state" returned from your server doesn't match the state that was sent.
`

Followed by the stacktrace of the error.

I made sure the the Firefly URL is the public one and that I've put the correct client ID. Both Firefly and Data Importer are accessible by public users.

**Comment by nr458h** [comment]
I tried again today and here are the logs - I replaced the domain name and the user name ... shall I also post the content of the MailError.php ??

```
2023-05-24 11:27:03] local.ERROR: Client exception when decoding response: Server error: `POST https://domain.tld/firefly/oauth/token` resulted in a `500 Internal Server Error` response:
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex, nofollow, n (truncated...)

[2023-05-24 11:27:03] local.ERROR: Response from server: "<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="robots" content="noindex, nofollow, noarchive, noodp, NoImageIndex, noydir">
    <title>Firefly III Exception :(</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <base href="https://domain.tld/firefly/">


        <link href="v1/lib/bs/css/bootstrap.min.css?v=" rel="stylesheet" type="text/css" nonce="Ecj/z76zk8GqHSgUHNa2JA==">
    <link href="v1/lib/fa/css/font-awesome.min.css?v=" rel="stylesheet" type="text/css" nonce="Ecj/z76zk8GqHSgUHNa2JA==">
    <link href="v1/css/daterangepicker.css?v=" rel="stylesheet" type="text/css" nonce="Ecj/z76zk8GqHSgUHNa2JA==">

        <link href="v1/lib/adminlte/css/AdminLTE.min.css?v=" rel="stylesheet" type="text/css" nonce="Ecj/z76zk8GqHSgUHNa2JA==">
    <link href="v1/lib/adminlte/css/skins/skin-blue-light.min.css?v=" rel="stylesheet" type="text/css" nonce="Ecj/z76zk8GqHSgUHNa2JA==">

        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png?v=3e8AboOwbd">
<link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png?v=3e8AboOwbd">
<link rel="manifest" href="manifest.webmanifest?v=3e8AboOwbd">
<link rel="mask-icon" href="safari-pinned-tab.svg" color="#3c8dbc">
<link rel="shortcut icon" href="favicon.ico?v=3e8AboOwbd">
<meta name="apple-mobile-web-app-title" content="Firefly III">
<meta name="application-name" content="Firefly III">
<meta name="msapplication-TileColor" content="#3c8dbc">
<meta name="msapplication-TileImage" content="mstile-144x144.png?v=3e8AboOwbd">
<meta name="theme-color" content="#3c8dbc">

<script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></head>
<body class="container">
<div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">
        <h1><a href="https://domain.tld/firefly"><strong>Firefly</strong>III</a></h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">
        <h3 class="text-info">Hoppla! Ein Fehler ist aufgetreten.</h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">
        <p>
            Leider konnte dieser Fehler nicht wiederhergestellt werden :(. Firefly III ist kaputt. Der Fehler ist:
        </p>
        <p class="text-danger">
            Expected response code &quot;250/251/252&quot; but got code &quot;553&quot;, with message &quot;553 5.7.1 &lt;user@domain.tld&gt;: Sender address rejected: not logged in&quot;.
        </p>
        <p>
            Dieser Fehler ist in der Datei <span style="font-family: monospace;">/var/www/firefly-iii/app/Jobs/MailError.php</span> in Zeile 103 mit dem Code 0 aufgetreten.
        </p>
    </div>
</div>
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1 col-md-12 col-sm-12 col-xs-12">
            <h4>
                Weitere Informationen
            </h4>
            <p>
                Bitte sammeln Sie weitere Informationen im Verzeichnis <code>storage/logs</code> wo Sie Logdateien finden können. Wenn Sie Docker verwenden, verwenden Sie <code>docker logs -f [container]</code>.
                Lesen Sie mehr über das Sammeln von Fehlerinformationen in <a href="https://docs.firefly-iii.org/faq/other#how-do-i-enable-debug-mode">der FAQ</a>.
            </p>
</body>
</html>
```

**Comment by pjpmosteiro** [comment]
The issue is with the way Firefly handles e-mail sending. When loggin in from FIDI or similar, it tries to send a email.

Changing 'default' on /var/www/firefly-iii/config/mail.php to "=> 'log' "should solve the issue for now.

![image](https://github.com/YunoHost-Apps/firefly-iii-di_ynh/assets/15787529/364db942-49e8-4769-8546-fb2c0160702b)

![image](https://github.com/YunoHost-Apps/firefly-iii-di_ynh/assets/15787529/1018289e-668b-4cd0-b7cd-35f5e8bcd40f)
